# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1576faeed87d81f4f4212f6a0f74dd1a426ac38207e642c9687cb4b62117bf82849bbf28eb38e8a5ee17d29dca37d0fa9ca6a12e4740abd3b4d8ac79ee8fceee

test:
  secret_key_base: 787b641b74563a4d4935203f99cdc23ca5c8b1d14729f5ab0cb62cc2ba0e470d8afdf5204e7c3a2f3488caff4eb64e78ee0b3e3046271c98e15c6a98f78cad09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
